-- PTLife Database
-- Seed: Search Aliases
--
-- Stable search vocabulary mapping user search terms to tags.

INSERT INTO search_aliases
    (id, alias, tag_id, language_code, priority, status)
VALUES
    (1,  'dance',                2,  'en',    10, 'active'),
    (2,  'modern dance',         2,  'en',    10, 'active'),
    (3,  'contemporary dance',   2,  'en',    10, 'active'),
    (4,  'dança contemporânea',  2,  'pt-PT', 10, 'active'),
    (5,  'ballet',               1,  'en',    10, 'active'),
    (6,  'ballet dance',         1,  'en',    20, 'active'),
    (7,  'balé',                 1,  'pt-PT', 20, 'active'),
    (8,  'classical',            3,  'en',    10, 'active'),
    (9,  'classical music',      3,  'en',    10, 'active'),
    (10, 'symphony',             3,  'en',    10, 'active'),
    (11, 'symphonic',            3,  'en',    20, 'active'),
    (12, 'música clássica',      3,  'pt-PT', 10, 'active'),
    (13, 'chamber music',        4,  'en',    10, 'active'),
    (14, 'quartet',              4,  'en',    20, 'active'),
    (15, 'string quartet',       4,  'en',    10, 'active'),
    (16, 'orchestra',            5,  'en',    10, 'active'),
    (17, 'orchestral',           5,  'en',    20, 'active'),
    (18, 'orquestra',            5,  'pt-PT', 10, 'active'),
    (19, 'opera',                6,  'en',    10, 'active'),
    (20, 'ópera',                6,  'pt-PT', 10, 'active'),
    (21, 'jazz',                 7,  'en',    10, 'active'),
    (22, 'fado',                 8,  'en',    10, 'active'),
    (23, 'rock',                 9,  'en',    10, 'active'),
    (24, 'pottery',             10,  'en',    10, 'active'),
    (25, 'pottery class',       10,  'en',    10, 'active'),
    (26, 'pottery workshop',    10,  'en',    10, 'active'),
    (27, 'ceramic',             11,  'en',    10, 'active'),
    (28, 'ceramics',            11,  'en',    10, 'active'),
    (29, 'cerâmica',            11,  'pt-PT', 10, 'active'),
    (30, 'painting',            12,  'en',    10, 'active'),
    (31, 'paint',               12,  'en',    20, 'active'),
    (32, 'pintura',             12,  'pt-PT', 10, 'active'),
    (33, 'sculpture',           13,  'en',    10, 'active'),
    (34, 'escultura',           13,  'pt-PT', 10, 'active'),
    (35, 'photography',         14,  'en',    10, 'active'),
    (36, 'photo exhibition',    14,  'en',    20, 'active'),
    (37, 'fotografia',          14,  'pt-PT', 10, 'active'),
    (38, 'sailing',             15,  'en',    10, 'active'),
    (39, 'sailboat',            15,  'en',    20, 'active'),
    (40, 'yacht',               15,  'en',    20, 'active'),
    (41, 'vela',                15,  'pt-PT', 10, 'active'),
    (42, 'kayak',               16,  'en',    10, 'active'),
    (43, 'kayaking',            16,  'en',    10, 'active'),
    (44, 'canoe',               16,  'en',    20, 'active'),
    (45, 'hike',                17,  'en',    10, 'active'),
    (46, 'hiking',              17,  'en',    10, 'active'),
    (47, 'walking trail',       17,  'en',    20, 'active'),
    (48, 'caminhada',           17,  'pt-PT', 10, 'active'),
    (49, 'cycling',             18,  'en',    10, 'active'),
    (50, 'bicycle',             18,  'en',    20, 'active'),
    (51, 'bike',                18,  'en',    20, 'active'),
    (52, 'ciclismo',            18,  'pt-PT', 10, 'active'),
    (53, 'castle',              19,  'en',    10, 'active'),
    (54, 'castel',              19,  'en',    30, 'active'),
    (55, 'fortress',            19,  'en',    20, 'active'),
    (56, 'fort',                19,  'en',    20, 'active'),
    (57, 'castelo',             19,  'pt-PT', 10, 'active'),
    (58, 'palace',              20,  'en',    10, 'active'),
    (59, 'palácio',             20,  'pt-PT', 10, 'active'),
    (60, 'monastery',           21,  'en',    10, 'active'),
    (61, 'mosteiro',            21,  'pt-PT', 10, 'active'),
    (62, 'architecture',        22,  'en',    10, 'active'),
    (63, 'arquitetura',         22,  'pt-PT', 10, 'active'),
    (64, 'history',             23,  'en',    10, 'active'),
    (65, 'historic',            23,  'en',    20, 'active'),
    (66, 'historical',          23,  'en',    20, 'active'),
    (67, 'história',            23,  'pt-PT', 10, 'active'),
    (68, 'museum',              24,  'en',    10, 'active'),
    (69, 'museums',             24,  'en',    10, 'active'),
    (70, 'museu',               24,  'pt-PT', 10, 'active'),
    (71, 'museus',              24,  'pt-PT', 10, 'active'),
    (72, 'gallery',             25,  'en',    10, 'active'),
    (73, 'art gallery',         25,  'en',    10, 'active'),
    (74, 'galeria',             25,  'pt-PT', 10, 'active'),
    (75, 'workshop',            26,  'en',    10, 'active'),
    (76, 'workshops',           26,  'en',    10, 'active'),
    (77, 'class',               26,  'en',    20, 'active'),
    (78, 'lecture',             27,  'en',    10, 'active'),
    (79, 'talk',                27,  'en',    20, 'active'),
    (80, 'seminar',             27,  'en',    20, 'active'),
    (81, 'palestra',            27,  'pt-PT', 10, 'active'),
    (82, 'film',                28,  'en',    10, 'active'),
    (83, 'movie',               28,  'en',    10, 'active'),
    (84, 'cinema',              28,  'en',    10, 'active'),
    (85, 'cinema',              28,  'pt-PT', 10, 'active'),
    (86, 'theatre',             29,  'en',    10, 'active'),
    (87, 'theater',             29,  'en',    10, 'active'),
    (88, 'play',                29,  'en',    20, 'active'),
    (89, 'teatro',              29,  'pt-PT', 10, 'active'),
    (90, 'comedy',              30,  'en',    10, 'active'),
    (91, 'stand up',            30,  'en',    20, 'active'),
    (92, 'stand-up',            30,  'en',    20, 'active'),
    (93, 'comédia',             30,  'pt-PT', 10, 'active');
